# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc4d1e7e50449ff9958e5c2b8e42ae39987c98b3de131a223dec89951886ec3e48a492b7653d752a37eafca4e940a668dcf1bcdb1e91d2d9f504528077eb99c

test:
  secret_key_base: aec29dd6eb700237920e9de231ebc5a596f9bfbcf934ae4b39dc237b18f4fc7a7eb7ba0bcda58b93ddd469ce7e53d0634c43bda60ef41beb0a70090b914b1219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
