# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec69424674cc1a34bc1d88427e0545a9af7c3aeac9f4a0b1779f3b8263ac048c5e6190604a1499f4403cb883d8e7d836ceb5a0e53f2ab6c38ee517cff5547896

test:
  secret_key_base: f9a64c32b02b77059fcd6550128f88a562689eef933bc93bc0495f33da19d04220d91d84c18d430b42c83e3130d31b7a033d56c840be314446d118beaac5a87d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
